### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by kalanityL** [pinakinathc/phocnet_keras#1]
Hi, 

Thank you very much for making these sources available. 

Would you consider providing a link to a pretrained model, (even if training was not completed), and a command line example on how to run a test image with this pretrained model?

Thank you,
K.

**Comment by pinakinathc** [comment]
@kalanityL please only use the network model and not the training/evaluation scripts.
regarding the pretrained model weights, the original author has them mentioned in his repository.

The link to download the weights for various datasets could be found in [this link](http://patrec.cs.tu-dortmund.de/cms/en/home/Resources/index.html)

also, I would suggest to give a read to [this](https://github.com/ssudholt/phocnet) repository (this is the original version developed by ssudholt. There you can also find link to a pytorch implementation of PHOCNet.

this was a rough implementation of phocnet and it has been quite some time. so i would not suggest you to use this repo for now.

------------------------------------

I would add a PHOCNet repo completely written using tensorflow within the next few weeks.
